### ISSUE TITLE
GPIO_GET_CHIPINFO_IOCTL fails

### ISSUE THREAD

**Issue by sssemil** [UncleGrumpy/spi-ch341-usb#5]
Was trying to get [this](https://codeberg.org/JF002/pinedio-lora-driver) to run, and the `GPIO_GET_CHIPINFO_IOCTL` call fails.

**Comment by sssemil** [comment]
Oops, permissions issue...

**Comment by UncleGrumpy** [comment]
If you use the `pinedio` branch of this repo, along with the `no-sudo` branch of [my pinedio-lora-driver fork](https://codeberg.org/Winford/pinedio-lora-driver/src/branch/no-sudo) it should just work, with no permission problems. If that doesn't work please let me know, and post the exact error message here, so I can investigate. I have submitted a PR to jf002 with these changes, so if everything works well it should end up in his official upstream  [pinedio-lora-driver](https://codeberg.org/JF002/pinedio-lora-driver) eventually.

**Comment by sssemil** [comment]
Those versions look better, but I still had to use sudo for usb-communicator. Looks like it get to a point of polling for messages, but I don't have any means of testing this atm.

**Comment by sssemil** [comment]
So, are GPIO's correct there? What is this issue about then https://github.com/UncleGrumpy/spi-ch341-usb/issues/3?
